before_all do
  update_fastlane
end

default_platform(:ios)

platform :ios do

  desc "Update app version"
  lane :update_version do
    package = load_json(json_path: "./../../package.json")
    increment_version_number(version_number: package["version"])
    increment_build_number()
  end

  desc "Push a new beta iOS build to Firebase App Distribution"
  lane :beta do
    setup_ci
    match(type: "appstore", readonly: is_ci)
    build_app(workspace: "App.xcworkspace", scheme: "App")
    firebase_app_distribution(
      app: ENV['FIREBASE_IOS_APP_ID'],
      groups: "iOS",
      release_notes: "Lots of amazing new features to test out!",
  )
  end
end
