before_all do
  update_fastlane
end

default_platform(:ios)

platform :ios do

  desc "Update app version"
  lane :update_version do
    package = load_json(json_path: "./../../package.json")
    increment_version_number(version_number: package["version"])
    increment_build_number()
  end

  desc "Push a new beta iOS build to Firebase App Distribution"
  lane :beta do
    sh("echo $CERTIFICATES_REPO_SSH_KEY > id_rsa_github_actions.rsa")
    setup_ci
    match(type: "appstore", readonly: is_ci, git_private_key: 'id_rsa_github_actions.rsa')
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_testflight(changelog: "Osom stuff!")
  end
end
