before_all do
  update_fastlane
end

default_platform(:ios)

platform :ios do

  desc "Update app version"
  lane :update_version do
    package = load_json(json_path: "./../../package.json")
    increment_version_number(version_number: package["version"])
    increment_build_number()
  end

  desc "Push a new beta iOS build to Testflight"
  lane :beta do
    setup_ci
    match(type: "appstore", readonly: is_ci, git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'])
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: 1346574507
    )
  end
end
