before_all do
  update_fastlane
end

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Push a new beta Android build to Firebase App Distribution"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release',
    )
    firebase_app_distribution(
      app: ENV['FIREBASE_ANDROID_APP_ID'],
      groups: "Android"
      release_notes: "Lots of amazing new features to test out!",
  )
  end
end
