on:
  push:
    branches:
    - angular
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install app
        run: npm install
      - name: Build app
        run: npx ng run intencje:app-shell:staging
      - name: Deploy to Firebase
        uses: pizzafox/firebase-action@1.0.7
        env:
          PROJECT_ID: "intencje-devel"
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: deploy --only hosting
